name: main

on:
  push:
    branches:
      - main
  pull_request: {}

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  formatting:
    name: 💅 Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Check code formatting
        run: yarn format:check

  lint:
    name: ⬣ ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Lint project
        run: yarn lint

  typecheck:
    name: 🔵 Typecheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Check types
        run: yarn typecheck
